version: '3.7'
services:
  mysql:
    image: mysql:5.7
    command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --default-time-zone='+9:00'"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: yatter
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_USER: yatter
      MYSQL_PASSWORD: yatter
    volumes:
      - "./.data/mysql:/var/lib/mysql"
      - "./ddl:/docker-entrypoint-initdb.d"
      # docより'コンテナ初回起動時に実行'とあったが, 
      # 実際にはdbデータを消すと毎起動で実行されることを確認
      # 逆にdbデータが残ったままでimageを消してから再起動したり, no-cacheでビルドしても実行されずに元のデータのみだった
    restart: on-failure

  testmysql:
    image: mysql:5.7
    command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --default-time-zone='+9:00'"
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: tatter
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_USER: tatter
      MYSQL_PASSWORD: tatter
    volumes:
      - "./.data/testmysql:/var/lib/mysql"
      - "./ddl:/docker-entrypoint-initdb.d"
    restart: on-failure
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql
      - PMA_USER=yatter
      - PMA_PASSWORD=yatter
    ports:
      - "3000:80"
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    working_dir: "/work/yatter-backend-go"
    command: ["air"]
    volumes:
      - ".:/work/yatter-backend-go"
      - "./.data/go-pkg:/go/pkg/mod/cache"
    ports:
      - "8080:8080"
    env_file:
      - ./env/docker-compose-default.env
      - ./env/docker-compose-test.env
    depends_on:
      - mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: on-failure

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    volumes:
      - ./openapi.yml:/data/openapi.yml
    environment:
      SWAGGER_JSON: /data/openapi.yml
